### ISSUE TITLE
[color-swatch] Stop supporting `swatch="none"`

### ISSUE THREAD

**Issue by DmitrySharabin** [color-js/elements#60]
We should remove this:

https://github.com/color-js/elements/blob/e8ec6d801de8b31dc8bf3a9cda34a13ef1817d6d/src/color-swatch/color-swatch.css#L112-L114

Instead, one can always do 

```css
::part(swatch) { display: none; }
```

if needed.
